/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShotsRouteImport } from './routes/shots'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as TripTripIdRouteImport } from './routes/trip.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotsRoute = ShotsRouteImport.update({
  id: '/shots',
  path: '/shots',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdRoute = TripTripIdRouteImport.update({
  id: '/trip/$tripId',
  path: '/trip/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shots': typeof ShotsRoute
  '/prices': typeof PricesRoute
  '/analytics': typeof AnalyticsRoute
  '/trips': typeof TripsRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shots': typeof ShotsRoute
  '/prices': typeof PricesRoute
  '/analytics': typeof AnalyticsRoute
  '/trips': typeof TripsRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shots': typeof ShotsRoute
  '/prices': typeof PricesRoute
  '/analytics': typeof AnalyticsRoute
  '/trips': typeof TripsRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scan' | '/settings' | '/shots' | '/prices' | '/analytics' | '/trips' | '/trip/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scan' | '/settings' | '/shots' | '/prices' | '/analytics' | '/trips' | '/trip/$tripId'
  id:
    | '__root__'
    | '/'
    | '/scan'
    | '/settings'
    | '/shots'
    | '/prices'
    | '/analytics'
    | '/trips'
    | '/trip/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  ShotsRoute: typeof ShotsRoute
  PricesRoute: typeof PricesRoute
  AnalyticsRoute: typeof AnalyticsRoute
  TripsRoute: typeof TripsRoute
  TripTripIdRoute: typeof TripTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shots': {
      id: '/shots'
      path: '/shots'
      fullPath: '/shots'
      preLoaderRoute: typeof ShotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId': {
      id: '/trip/$tripId'
      path: '/trip/$tripId'
      fullPath: '/trip/$tripId'
      preLoaderRoute: typeof TripTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  ShotsRoute: ShotsRoute,
  PricesRoute: PricesRoute,
  AnalyticsRoute: AnalyticsRoute,
  TripsRoute: TripsRoute,
  TripTripIdRoute: TripTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
